FROM nvidia/cuda:10.2-base-ubuntu18.04

ENV TZ=Europe/Vienna
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && \
    apt-get install -y sudo wget bash zip git rsync build-essential software-properties-common ca-certificates xvfb vim cmake-curses-gui

RUN apt-get install -y python3.6-dev python3-pip

RUN python3.6 -m pip install pip --upgrade

RUN apt-get install -y cmake libeigen3-dev libboost-all-dev

# For PCL
RUN apt-get install -y libflann-dev libvtk6-dev libusb-1.0.0-dev

RUN python3.6 -m pip install numpy \
                             scikit-learn \
                             open3d==0.9.0.0

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1 && \
    update-alternatives --set python /usr/bin/python3.6

# ==================================================================
# config & cleanup
# ------------------------------------------------------------------
RUN ldconfig && \
    apt-get clean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* /tmp/* ~/*
